# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Load RVM into a shell session *as a function*
if [[ -s "$HOME/.rvm/scripts/rvm" ]] ; then
 # First try to load from a user install
 source "$HOME/.rvm/scripts/rvm"
elif [[ -s "/usr/local/rvm/scripts/rvm" ]] ; then
 # Then try to load from a root install
 source "/usr/local/rvm/scripts/rvm"
else
 printf "ERROR: An RVM installation was not found.\n"
fi

# VIM mode
bindkey -v
bindkey "^R" history-incremental-search-backward

# Execute the config files in .zsh.after
for config_file ($HOME/.zsh.after/*.zsh) source $config_file
