---
- name: "Copy install script for bitcoind"
  template: src=install_bitcoind.rb.j2 dest={{home_dir}}/install_bitcoind.rb

- name: "Download and install bitcoind v0.8.0"
  shell: ruby install_bitcoind.rb creates={{home_dir}}/bitcoin-0.8.0-linux

- name: Add bitcoind to path
  template: src=bitcoind.zsh.j2 dest={{home_dir}}/.zsh.after/bitcoind.zsh
