---
- name: install required apt packages
  apt: name={{item}} state=present
  sudo: True
  with_items:
    - tmux
    - zsh
    - git

- name: clone prezto
  shell: git clone --recursive https://github.com/sorin-ionescu/prezto.git "${ZDOTDIR:-$HOME}/.zprezto" creates="{{home_dir}}/.zprezto"

# - name: install prezto
#   shell: "{{home_dir}}/install_prezto.sh creates={{home_dir}}/.zshrc"
# 
# - name: change to zsh
#   shell: zsh
- name: zsh facts
  shell: 'echo $SHELL'
  register: default_shell
  # changed when determines when will this task be considered changed when running
  # ansible. In this case, we want it to always be false, as we are just
  # retrieving information.
  changed_when: False
  sudo: no

# - name: set EXTENDED_GLOB
#   shell: setopt EXTENDED_GLOB

# - name: make default shell zsh
#   shell: chsh -s /bin/zsh
# Now, we want to set zsh as the default shell, unless it is already the default
# one.
- name: make zsh default
  user: name={{username}} shell=/bin/zsh
  sudo: True
  # shell:  chsh -s /bin/zsh 
  # This task will run only when the following is true. In here, we check the
  # value registered previously within the "default_shell" variable.
  # when: default_shell.stdout.find('/bin/zsh') == -1

- name: copy zsh files
  # shell: /bin/zsh -c 'setopt EXTENDED_GLOB && for rcfile in "${ZDOTDIR:-$HOME}"/.zprezto/runcoms/^README.md(.N); do ln -s "$rcfile" "${ZDOTDIR:-$HOME}/.${rcfile:t}"' done creates={{home_dir}}/.zshrc
  shell: ln -s {{home_dir}}/.zprezto/runcoms/{{item}} {{home_dir}}/.{{item}} creates={{home_dir}}/.{{item}}
  with_items:
    - zlogin
    - zlogout
    - zpreztorc
    - zprofile
    - zshenv
    - zshrc

- name: copy tmux config
  copy: "src=tmux.conf dest={{home_dir}}/.tmux.conf"

- name: copy zshrc
  copy: src=zshrc dest={{home_dir}}/.zshrc

- name: Copy vim mode
  copy: src=vim-mode.zsh dest={{home_dir}}/.zsh.after/vim-mode.zsh

- name: Create .zsh.after for hooks
  shell: "mkdir {{home_dir}}/.zsh.after creates={{home_dir}}/.zsh.after"
