---
- name: Install required packages
  apt: name={{item}} state=present
  sudo: True
  with_items:
    - htop
    - nginx
    - ack-grep
    - libcurl4-openssl-dev
    - libxml2-dev
    - redis-server
    - libxslt1-dev

- name: Ensure known_hosts exists
  shell: touch {{home_dir}}/.ssh/known_hosts creates={{home_dir}}/.ssh/known_hosts

- name: Ensure github is not in the known hosts
  shell: ssh-keygen -R github.com

- name: Add github to known ssh hosts
  shell: ssh-keyscan github.com >> {{home_dir}}/.ssh/known_hosts
